### ISSUE TITLE
Gitlab CI now has persistent auto devops deploy tokens for kubernetes

### ISSUE THREAD

**Issue by jonathanjfshaw** [lifechurch/k8s-deploy-helper#14]
https://about.gitlab.com/2018/06/22/gitlab-11-0-released/#persistent-auto-devops-deploy-tokens-for-kubernetes

So no need for the dedicated gitlab user to handle redeployments in the event of pod reboot.

**Comment by WillPlatnick** [comment]
Sorry for the late reply, my notification settings were wrong. Thanks, in the next backwards incompatible release we will use this token and put in directions on how to generate it.

**Comment by WillPlatnick** [comment]
Fixed in https://github.com/lifechurch/k8s-deploy-helper/pull/16
