### ISSUE TITLE
Error during load comman.bash script

### ISSUE THREAD

**Issue by pawelkasperek** [lifechurch/k8s-deploy-helper#19]
HI,

I have follow error when I run build script:

: invalid option nameripts/common.bash: line 1: set: pipefail

I know how works set pipefail but what is the reason of this error ?

**Comment by WillPlatnick** [comment]
@pawelkasperek I've never seen that before. Can you post more context please?

**Comment by WillPlatnick** [comment]
Closing as this issue is stale.
