### ISSUE TITLE
kubeval should evaluate the rendered templates

### ISSUE THREAD

**Issue by nabadger** [lifechurch/k8s-deploy-helper#21]
In the deploy script should `kubeval` not run against the yaml files in rendered in `/tmp/kubernetes`?

Currently it runs against files in `./kubernetes` in the project repo.

This crashes for me, because I'm using a $PORT environment (in my project manifests) via the CI/CD pipeline variables (which envsubst will set).

**Comment by WillPlatnick** [comment]
@nabadger It absolutely should, I have a branch in that fixes that that should release this week.

**Comment by WillPlatnick** [comment]
In the meantime, 3.0.0 is unaffected.

**Comment by nabadger** [comment]
Thanks :)

**Comment by WillPlatnick** [comment]
This is fixed in 3.1.0.
