### ISSUE TITLE
Allow kubeval to be skipped

### ISSUE THREAD

**Issue by antonydenyer** [lifechurch/k8s-deploy-helper#28]
I'm applying a certificate on each deployment but they are [not supported](https://github.com/garethr/kubeval/issues/66) by kubeval. Can you provide a way to skip validation for some yaml files?

**Comment by WillPlatnick** [comment]
@antonydenyer - We are working on a way to skip specific API types

**Comment by WillPlatnick** [comment]
@antonydenyer Starting with KDH 5.0.0, you can set KDH_SKIP_KUBEVAL to true.
